[wordlist]
# default field separator
separator = ,
# default newline character(s)
newline = \n
# column labels that contain Japanese words, separated by space (in order of preference)
ja_columns = ja kana
# column labels that contain sounds, separated by space
sound_columns = sound

[forvo]
cache = ~/.jptool/forvo.csv
preferred_users = strawberrybrown
perferred_countries = Japon

[sounds]
path = ~/.jptool/sounds
