[wordlist]
# default field separator
separator = ,
# default newline character(s)
newline = \n

[forvo]
cache = ~/.jptool/forvo.csv
preferred_users = strawberrybrown
perferred_countries = Japon

[sounds]
path = ~/.jptool/sounds
